name: Deploy to Netlify

on:
  push:
    branches:
      - main # Trigger workflow when changes are pushed to the main branch

jobs:
  deploy-to-netlify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v20.17.0" # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build # Ensure this matches your actual build command

      - name: Deploy to Netlify
        if: success() # Runs only if the build step is successful
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --dir=.next # Ensure this directory matches your build output
